language: node_js
sudo: false
node_js:
- '5.9.1'

env:
  global:
  - GH_REF: github.com/orizens/echoes-ng2.git
  - secure: iVvuhPQuwZWkWJCum1kQk+cj4O/qEcwOaO0gMjpPudmAhHx3cJY3y5OAWZ40DaESFEPjLTPhqVbmDAvrz2Cuqd6GnNcbiMdXz70pqtPnKceSD1YJWkmrYQClNgrI/u+4EmC3/OoNnhD/V/kyS2YTaaUC/QdXOkTnst7Mybm6Tlk=
  - secure: WZg+QI6a2dy6afRjeRypsIaXLiKueizEY/mRgRzjbqwRQSBttHdCVR2Hdba7R59myJBzsKLVceHD3nbEKVUc/eYo+oQtQsL/t44rq3HeGYoGt1qq87qk03GsA0/X7600NA1tenDkk7TtAy2RVBa7vHtanHMfpcgogIFXfKqqsqU=
  - secure: ZjBfq/AblPpn54B9V9KUp+bwlASMZkzzCBa3G9pOhPDaGStY3I5PpHBxmbk+QzleC2auJLwL3Fpwip4CnzHT+5aD+VMwIjqb+PKGSdRhRUjIJMSchwxhXeUU1l9FcF30jH+Fw/r1Nq2Fw/LRNGXGqLezIBcBjcAB0KA9svgZz2w=

install:
# - npm install -g protractor babel
- npm install karma-es6-shim
- npm install
before_script:
# - ./BrowserStackLocal-linux $bs_key localhost,9001,0 &
# - npm start &
# - sleep 5
after_script:
- process.exit()
after_success:
- chmod +x ./config/deploy.sh
- ./config/deploy.sh
cache:
  directories:
  - $HOME/.nvm
  - node_modules
